package com.gpcbellary.cms.config;
import com.gpcbellary.cms.model.*; import com.gpcbellary.cms.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import java.math.BigDecimal; import java.time.LocalDate;
@Configuration public class ProfessionalDataInitializer {
 @Bean CommandLineRunner seedProfessional(AdmissionRepository a,ResultRepository r,CompanyRepository c,CollegeRuleRepository rules){return args->{
  if(a.count()==0){a.save(adm("ADM-2026-001","Priya Sharma","Ramesh Sharma","Sunita Sharma","Female","9888000011","priya@example.com","CSE","SSLC / 10th","Bellary, Karnataka","SUBMITTED",LocalDate.of(2026,9,28)));a.save(adm("ADM-2026-002","Mohammed Ayaan","Irfan Ahmed","Shabana Begum","Male","9888000012","ayaan@example.com","ECE","SSLC / 10th","Bellary, Karnataka","UNDER_REVIEW",LocalDate.of(2026,9,27)));}
  if(r.count()==0){r.save(res("2025-26","Diploma Final Examination","GPC25CSE001","Nithin Kumar","CSE","82.40","PASS"));r.save(res("2025-26","Diploma Final Examination","GPC25CSE002","Divya Rao","CSE","91.20","PASS"));r.save(res("2025-26","Diploma Final Examination","GPC25ECE001","Manoj Kumar","ECE","78.60","PASS"));r.save(res("2025-26","Diploma Final Examination","GPC25ME001","Kavya Patil","ME","86.10","PASS"));}
  if(c.count()==0){c.save(co("Infosys","Systems Engineer","Bengaluru","Diploma / relevant technical qualification","Placement Cell","placements@example.com","OPEN"));c.save(co("Tata Electronics","Technician / Trainee","Bengaluru","Diploma in ECE/EEE/ME","HR Team","careers@example.com","OPEN"));c.save(co("TVS Motors","Technician Trainee","Hosur","Diploma in Mechanical","Placement Cell","hr@example.com","UPCOMING"));c.save(co("Bosch","Junior Technical Associate","Bengaluru","Diploma in ME/ECE/EEE","HR Desk","careers@example.com","OPEN"));}
  if(rules.count()==0){rules.save(rule("Academic","Attendance","Students should maintain the minimum attendance prescribed by the institution and follow the approved process for leave or supporting documents."));rules.save(rule("Campus","Identity Card","Students must carry a valid college identity card on campus and present it when requested."));rules.save(rule("Discipline","Code of Conduct","Maintain respectful behaviour, follow staff instructions and do not damage college property."));rules.save(rule("Examination","Examination Rules","Follow examination-hall instructions, carry permitted materials only and report at the prescribed time."));rules.save(rule("Library","Library Rules","Maintain silence, return books on time and handle library resources responsibly."));rules.save(rule("Safety","Laboratory Safety","Use laboratory equipment only as instructed and follow department safety procedures."));}
 };}
 private Admission adm(String n,String a,String f,String m,String g,String p,String e,String b,String q,String ad,String s,LocalDate d){Admission x=new Admission();x.setApplicationNo(n);x.setApplicantName(a);x.setFatherName(f);x.setMotherName(m);x.setGender(g);x.setPhone(p);x.setEmail(e);x.setBranch(b);x.setPreviousQualification(q);x.setAddress(ad);x.setStatus(s);x.setApplicationDate(d);return x;}
 private Result res(String y,String ex,String u,String n,String b,String p,String s){Result x=new Result();x.setAcademicYear(y);x.setExamName(ex);x.setUsn(u);x.setStudentName(n);x.setBranch(b);x.setPercentage(new BigDecimal(p));x.setResultStatus(s);return x;}
 private Company co(String n,String role,String loc,String el,String person,String email,String st){Company x=new Company();x.setCompanyName(n);x.setJobRole(role);x.setLocation(loc);x.setEligibility(el);x.setContactPerson(person);x.setContactEmail(email);x.setStatus(st);return x;}
 private CollegeRule rule(String c,String t,String d){CollegeRule x=new CollegeRule();x.setCategory(c);x.setTitle(t);x.setDescription(d);return x;}
}
